version: '3.4'

services:
  journals.api:
    image: ${DOCKER_REGISTRY-}journalsapi
    build:
      context: .
      dockerfile: Services/Journals/Journals.API/Dockerfile

  submission.api:
    image: ${DOCKER_REGISTRY-}submissionapi
    build:
      context: .
      dockerfile: Services/Submission/Submission.API/Dockerfile

  production.api:
    image: ${DOCKER_REGISTRY-}productionapi
    build:
      context: .
      dockerfile: Services/Production/Production.API/Dockerfile

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile
  
  productiondb:
    image: mcr.microsoft.com/mssql/server

  redisdb:
    image: redis/redis-stack
