version: '3.4'

services:
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=productiondb;Database=AuthDb;User Id=sa;Password=Production123;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - productiondb
    ports:
      - "9001:8080"
      - "9051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # submission.api:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ConnectionStrings__Database=Server=productiondb;Database=SubmissionDb;User Id=sa;Password=Production123;Encrypt=False;TrustServerCertificate=True
  #   depends_on:
  #     - productiondb
  #   ports:
  #     - "9004:8080"
  #     - "9054:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  

  production.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=productiondb;Database=ProductionDb;User Id=sa;Password=Production123;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - productiondb
    ports:
      - "9002:8080"
      - "9052:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  journals.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=redis://redisdb
    depends_on:
      - redisdb
    ports:
      - "9003:8080"
      - "9053:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  productiondb:
    container_name: productiondb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Production123
    restart: always
    ports:
      - "1433:1433" 

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
