// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Persistence;

#nullable disable

namespace Review.Persistence.Migrations
{
    [DbContext(typeof(ReviewDbContext))]
    [Migration("20250731135005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("Stage");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("Title");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ArticleAction", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleActor", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("AUT");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ArticleId", "PersonId", "Role");

                    b.HasIndex("PersonId");

                    b.ToTable("ArticleActor", (string)null);

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("ArticleActor");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleStageTransition", b =>
                {
                    b.Property<string>("CurrentStage")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinationStage")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CurrentStage", "ActionType", "DestinationStage");

                    b.ToTable("ArticleStageTransition", (string)null);

                    b.HasData(
                        new
                        {
                            CurrentStage = "InReview",
                            ActionType = "UploadReviewReport",
                            DestinationStage = "InReview"
                        },
                        new
                        {
                            CurrentStage = "InReview",
                            ActionType = "UploadReviewReport",
                            DestinationStage = "AwaitingDecision"
                        },
                        new
                        {
                            CurrentStage = "AwaitingDecision",
                            ActionType = "AcceptArticle",
                            DestinationStage = "Accepted"
                        },
                        new
                        {
                            CurrentStage = "AwaitingDecision",
                            ActionType = "RejectArticle",
                            DestinationStage = "Rejected"
                        });
                });

            modelBuilder.Entity("Review.Domain.Articles.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.ComplexProperty<Dictionary<string, object>>("File", "Review.Domain.Articles.Asset.File#File", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FileServerId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("OriginalName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasComment("Original full file name, with extension");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasComment("Size of the file in kilobytes");

                            b1.ComplexProperty<Dictionary<string, object>>("Extension", "Review.Domain.Articles.Asset.File#File.Extension#FileExtension", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("nvarchar(8)")
                                        .HasColumnName("File_Extension");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Name", "Review.Domain.Articles.Asset.File#File.Name#FileName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("File_Name")
                                        .HasComment("Final name of the file after renaming");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "Review.Domain.Articles.Asset.Name#AssetName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("Type");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Articles.AssetTypeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFileExtension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("pdf");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(2);

                    b.Property<byte>("MaxAssetCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("MaxFileSizeInMB")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.ComplexProperty<Dictionary<string, object>>("AllowedFileExtensions", "Review.Domain.Articles.AssetTypeDefinition.AllowedFileExtensions#FileExtensions", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Extensions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AllowedFileExtensions");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetTypeDefinition", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Articles.ReviewInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<int>("SentById")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Review.Domain.Articles.ReviewInvitation.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token", "Review.Domain.Articles.ReviewInvitation.Token#InvitationToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Token");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("SentById");

                    b.ToTable("ReviewInvitation", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Articles.Stage", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(2);

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Description = "The Author created the article",
                            Info = "The article was created. Please upload the Manuscript and the Supplimentarry materials. Associate the authors with the article.",
                            Name = "Created"
                        },
                        new
                        {
                            Id = 102,
                            Description = "The Manuscript was submitted by the author",
                            Info = "Our editorial specialist is checking your article. We will contact you if we need any further files or information.",
                            Name = "ManuscriptUploaded"
                        },
                        new
                        {
                            Id = 103,
                            Description = "Author uploaded the Manuscript",
                            Info = "The manuscript was uploaded, you can now submit the article.",
                            Name = "Submitted"
                        },
                        new
                        {
                            Id = 104,
                            Description = "Article was rejected by the editorial specialist",
                            Info = "The manuscript does not reach the required quality standard of this journal.",
                            Name = "InitialRejected"
                        },
                        new
                        {
                            Id = 105,
                            Description = "Article approved",
                            Info = "Your article has been checked. Our editorial specialists will start soon revieing it.",
                            Name = "InitialApproved"
                        },
                        new
                        {
                            Id = 201,
                            Description = "Article approved",
                            Info = "Our editorial specialist is reviewing your article.",
                            Name = "InReview"
                        },
                        new
                        {
                            Id = 204,
                            Description = "Article accepted",
                            Info = "Your article has been reviewed and accepted. The production of the article will start soon.",
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = 300,
                            Description = "Typesetter assigned",
                            Info = "The typesetter is preparing your Author’s Proof. We will contact you if we need any further files or information.",
                            Name = "InProduction"
                        },
                        new
                        {
                            Id = 301,
                            Description = "Author's proof approved",
                            Info = "The Author's Proof is available for you to check and provide corrections. This status is also displayed if we are preparing a further Author's Proof at your request.",
                            Name = "DraftProduction"
                        },
                        new
                        {
                            Id = 302,
                            Description = "Publisher's proof uploaded",
                            Info = "The typesetter is preparing the final version of your article for publication. We will contact you if we need to check anything further before publication.",
                            Name = "FinalProduction"
                        },
                        new
                        {
                            Id = 304,
                            Description = "Article scheduled for publication",
                            Info = "Your Production Specialist has completed their quality checks. Your article is now scheduled for publication on our website and will appear online within the next few working days.",
                            Name = "PublicationScheduled"
                        },
                        new
                        {
                            Id = 305,
                            Description = "Article published",
                            Info = "Your article has been published and sent to all relevant repositories, and the publication process is now complete. Please note that repositories have different processing times and your article may not be available yet.",
                            Name = "Published"
                        });
                });

            modelBuilder.Entity("Review.Domain.Articles.StageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("StageId");

                    b.ToTable("StageHistory", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Reviewers.ReviewerSpecialization", b =>
                {
                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("JournalId", "ReviewerId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ReviewerSpecialization", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Shared.Journal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Journal", (string)null);
                });

            modelBuilder.Entity("Review.Domain.Shared.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("Institution or organization they are associated with when they conduct their research.");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Honorific")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "Review.Domain.Shared.Person.Email#EmailAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("Email");
                        });

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("Person");

                    b
                        .UseTphMappingStrategy()
                        .HasAnnotation("RawSql:Index", "CREATE UNIQUE INDEX IX_Person_Email_TypeDiscriminator ON Person (Email, TypeDiscriminator)");
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleAuthor", b =>
                {
                    b.HasBaseType("Review.Domain.Articles.ArticleActor");

                    b.Property<string>("ContributionAreas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ArticleActor", (string)null);

                    b.HasDiscriminator().HasValue("ArticleAuthor");
                });

            modelBuilder.Entity("Review.Domain.Articles.Author", b =>
                {
                    b.HasBaseType("Review.Domain.Shared.Person");

                    b.Property<string>("Degree")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasComment("The author's highest academic qualification (e.g., PhD in Mathematics, MSc in Chemistry).");

                    b.Property<string>("Discipline")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("The author's main field of study or research (e.g., Biology, Computer Science).");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("Review.Domain.Reviewers.Reviewer", b =>
                {
                    b.HasBaseType("Review.Domain.Shared.Person");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator().HasValue("Reviewer");
                });

            modelBuilder.Entity("Review.Domain.Articles.Editor", b =>
                {
                    b.HasBaseType("Review.Domain.Reviewers.Reviewer");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator().HasValue("Editor");
                });

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.HasOne("Review.Domain.Shared.Journal", "Journal")
                        .WithMany("Articles")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Review.Domain.Articles.Stage", null)
                        .WithMany()
                        .HasForeignKey("Stage")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Journal");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleAction", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", null)
                        .WithMany("Actions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review.Domain.Articles.ArticleActor", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", "Article")
                        .WithMany("Actors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "Person")
                        .WithMany("ArticleActors")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Review.Domain.Articles.Asset", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", "Article")
                        .WithMany("Assets")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Articles.AssetTypeDefinition", "TypeRef")
                        .WithMany()
                        .HasForeignKey("Type")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("TypeRef");
                });

            modelBuilder.Entity("Review.Domain.Articles.ReviewInvitation", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", null)
                        .WithMany("Invitations")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Shared.Person", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("Review.Domain.Articles.StageHistory", b =>
                {
                    b.HasOne("Review.Domain.Articles.Article", null)
                        .WithMany("StageHistories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Articles.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Review.Domain.Reviewers.ReviewerSpecialization", b =>
                {
                    b.HasOne("Review.Domain.Shared.Journal", "Journal")
                        .WithMany("Reviewers")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Review.Domain.Reviewers.Reviewer", "Reviewer")
                        .WithMany("Specializations")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Review.Domain.Articles.Article", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Actors");

                    b.Navigation("Assets");

                    b.Navigation("Invitations");

                    b.Navigation("StageHistories");
                });

            modelBuilder.Entity("Review.Domain.Shared.Journal", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Reviewers");
                });

            modelBuilder.Entity("Review.Domain.Shared.Person", b =>
                {
                    b.Navigation("ArticleActors");
                });

            modelBuilder.Entity("Review.Domain.Reviewers.Reviewer", b =>
                {
                    b.Navigation("Specializations");
                });
#pragma warning restore 612, 618
        }
    }
}
