// <auto-generated />
using System;
using ArticleHub.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArticleHub.Persistence.Migrations
{
    [DbContext(typeof(ArticleHubDbContext))]
    [Migration("20241202073713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleHub.Domain.Article", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("AcceptedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("acceptedon");

                    b.Property<string>("Doi")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("doi");

                    b.Property<int>("JournalId")
                        .HasColumnType("integer")
                        .HasColumnName("journalid");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("publishedon");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<int>("SubmittedById")
                        .HasColumnType("integer")
                        .HasColumnName("submittedbyid");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submittedon");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasIndex("JournalId");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("Title");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("ArticleHub.Domain.ArticleContributor", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("articleid");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("personid");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AUT")
                        .HasColumnName("role");

                    b.HasKey("ArticleId", "PersonId", "Role")
                        .HasName("pk_articlecontributor");

                    b.HasIndex("PersonId");

                    b.ToTable("articlecontributor", (string)null);
                });

            modelBuilder.Entity("ArticleHub.Domain.Journal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_journal");

                    b.ToTable("journal", (string)null);
                });

            modelBuilder.Entity("ArticleHub.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lastname");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("ArticleHub.Domain.Article", b =>
                {
                    b.HasOne("ArticleHub.Domain.Journal", "Journal")
                        .WithMany("Articles")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_journal_journalid");

                    b.HasOne("ArticleHub.Domain.Person", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_person_submittedbyid");

                    b.Navigation("Journal");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("ArticleHub.Domain.ArticleContributor", b =>
                {
                    b.HasOne("ArticleHub.Domain.Article", null)
                        .WithMany("Contributors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_articlecontributor_article_articleid");

                    b.HasOne("ArticleHub.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_articlecontributor_person_personid");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ArticleHub.Domain.Article", b =>
                {
                    b.Navigation("Contributors");
                });

            modelBuilder.Entity("ArticleHub.Domain.Journal", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
