// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Production.Persistence;

#nullable disable

namespace Production.Persistence.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    partial class ProductionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Production.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 13, 14, 36, 9, 496, DateTimeKind.Utc).AddTicks(5151));

                    b.Property<string>("Doi")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("JournalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SubmitedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("VolumeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JournalId");

                    b.HasIndex("PublishedById");

                    b.HasIndex("Stage");

                    b.HasIndex("SubmitedById");

                    b.HasIndex("Title");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.ArticleActor", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("AUT");

                    b.HasKey("ArticleId", "PersonId", "Role");

                    b.HasIndex("PersonId");

                    b.ToTable("ArticleActor", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.ArticleCurrentStage", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("ArticleId");

                    b.HasIndex("Stage");

                    b.ToTable("ArticleCurrentStage", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("AssetNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 13, 14, 36, 9, 507, DateTimeKind.Utc).AddTicks(3385));

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<int>("LatestFileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TypeCode");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.AssetAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetAction", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.AssetLatestFile", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.HasKey("AssetId");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("AssetLatestFile", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedFileExtentions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DefaultCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFileExtension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasDefaultValue("pdf");

                    b.Property<byte>("MaxNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssetType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedFileExtentions = "[\"pdf\"]",
                            Code = "Manuscript",
                            DefaultCategoryId = 1,
                            DefaultFileExtension = "pdf",
                            MaxNumber = (byte)0,
                            Name = "Manuscript"
                        },
                        new
                        {
                            Id = 2,
                            AllowedFileExtentions = "[\"pdf\"]",
                            Code = "ReviewReport",
                            DefaultCategoryId = 3,
                            DefaultFileExtension = "pdf",
                            MaxNumber = (byte)0,
                            Name = "Reviewer Report"
                        },
                        new
                        {
                            Id = 3,
                            AllowedFileExtentions = "[\"pdf\"]",
                            Code = "DraftPdf",
                            DefaultCategoryId = 3,
                            DefaultFileExtension = "pdf",
                            MaxNumber = (byte)0,
                            Name = "Draft PDF"
                        },
                        new
                        {
                            Id = 4,
                            AllowedFileExtentions = "[\"pdf\"]",
                            Code = "FinalPdf",
                            DefaultCategoryId = 3,
                            DefaultFileExtension = "pdf",
                            MaxNumber = (byte)0,
                            Name = "Final PDF"
                        },
                        new
                        {
                            Id = 5,
                            AllowedFileExtentions = "[\"zip\"]",
                            Code = "FinalHtml",
                            DefaultCategoryId = 3,
                            DefaultFileExtension = "zip",
                            MaxNumber = (byte)0,
                            Name = "Final HTML Zip"
                        },
                        new
                        {
                            Id = 6,
                            AllowedFileExtentions = "[\"epub\"]",
                            Code = "FinalEpub",
                            DefaultCategoryId = 3,
                            DefaultFileExtension = "epub",
                            MaxNumber = (byte)0,
                            Name = "Final Epub"
                        },
                        new
                        {
                            Id = 7,
                            AllowedFileExtentions = "[\"jpg\",\"png\",\"tif\",\"tiff\",\"eps\"]",
                            Code = "Figure",
                            DefaultCategoryId = 2,
                            DefaultFileExtension = "tif",
                            MaxNumber = (byte)12,
                            Name = "HTML Figure"
                        },
                        new
                        {
                            Id = 8,
                            AllowedFileExtentions = "[\"csv\",\"xls\"]",
                            Code = "DataSheet",
                            DefaultCategoryId = 2,
                            DefaultFileExtension = "csv",
                            MaxNumber = (byte)12,
                            Name = "Data Sheet"
                        },
                        new
                        {
                            Id = 9,
                            AllowedFileExtentions = "[]",
                            Code = "SupplementaryFile",
                            DefaultCategoryId = 2,
                            DefaultFileExtension = "pdf",
                            MaxNumber = (byte)12,
                            Name = "Supplementary File"
                        });
                });

            modelBuilder.Entity("Production.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "TypeId")
                        .IsUnique();

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 9, 13, 14, 36, 9, 514, DateTimeKind.Utc).AddTicks(1682));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FileServerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<int>("LatestActionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasComment("Final name of the file after renaming");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasComment("Full file name, with extension");

                    b.Property<int>("Size")
                        .HasColumnType("int")
                        .HasComment("Size of the file in kilobytes");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("File", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.FileAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LasModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("FileAction", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.FileLatestAction", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("ActionId")
                        .IsUnique();

                    b.ToTable("FileLatestAction", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("DefaultTypesetterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTypesetterId");

                    b.ToTable("Journal", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Production.Domain.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stage", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Code = "Submitted",
                            Description = "Our editorial specialist is checking your article. We will contact you if we need any further files or information.",
                            Name = "Article submitted"
                        },
                        new
                        {
                            Id = 200,
                            Code = "InReview",
                            Description = "Your article has been checked and article. Our editorial specialists will start soon revieing it.",
                            Name = "Article approved"
                        },
                        new
                        {
                            Id = 201,
                            Code = "Accepted",
                            Description = "Your article has been reviewed and accepted. The production of the article will start soon.",
                            Name = "Article accepted"
                        },
                        new
                        {
                            Id = 300,
                            Code = "InProduction",
                            Description = "The typesetter is preparing your Author’s Proof. We will contact you if we need any further files or information.",
                            Name = "Typesetter assigned"
                        },
                        new
                        {
                            Id = 301,
                            Code = "AuthorsProof",
                            Description = "The Author's Proof is available for you to check and provide corrections. This status is also displayed if we are preparing a further Author's Proof at your request.",
                            Name = "Author's proof approved"
                        },
                        new
                        {
                            Id = 302,
                            Code = "FinalProduction",
                            Description = "The typesetter is preparing the final version of your article for publication. We will contact you if we need to check anything further before publication.",
                            Name = "Publisher's proof uploaded"
                        },
                        new
                        {
                            Id = 303,
                            Code = "PublisherProof",
                            Description = "Your Production Specialist is applying quality checks to ensure your article is ready for publication.",
                            Name = "Article scheduled for publication"
                        },
                        new
                        {
                            Id = 304,
                            Code = "PublicationScheduled",
                            Description = "Your Production Specialist has completed their quality checks. Your article is now scheduled for publication on our website and will appear online within the next few working days.",
                            Name = "Article scheduled for publication"
                        },
                        new
                        {
                            Id = 305,
                            Code = "Published",
                            Description = "Your article has been published and sent to all relevant repositories, and the publication process is now complete. Please note that repositories have different processing times and your article may not be available yet.",
                            Name = "Article published"
                        });
                });

            modelBuilder.Entity("Production.Domain.Entities.StageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("StageId");

                    b.ToTable("StageHistory", (string)null);
                });

            modelBuilder.Entity("Production.Domain.Entities.Author", b =>
                {
                    b.HasBaseType("Production.Domain.Entities.Person");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Country")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasIndex("ArticleId");

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("Production.Domain.Entities.Typesetter", b =>
                {
                    b.HasBaseType("Production.Domain.Entities.Person");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.ToTable("Person", (string)null);

                    b.HasDiscriminator().HasValue("Typesetter");
                });

            modelBuilder.Entity("Production.Domain.Entities.Article", b =>
                {
                    b.HasOne("Production.Domain.Entities.Journal", "Journal")
                        .WithMany("Articles")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.Person", "PublishedBy")
                        .WithMany()
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Production.Domain.Entities.Stage", null)
                        .WithMany()
                        .HasForeignKey("Stage")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.Person", "SubmitedBy")
                        .WithMany()
                        .HasForeignKey("SubmitedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Journal");

                    b.Navigation("PublishedBy");

                    b.Navigation("SubmitedBy");
                });

            modelBuilder.Entity("Production.Domain.Entities.ArticleActor", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", "Article")
                        .WithMany("Actors")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.Person", "Person")
                        .WithMany("ArticleActors")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Production.Domain.Entities.ArticleCurrentStage", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", "Article")
                        .WithOne("CurrentStage")
                        .HasForeignKey("Production.Domain.Entities.ArticleCurrentStage", "ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.Stage", null)
                        .WithMany()
                        .HasForeignKey("Stage")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Production.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", "Article")
                        .WithMany("Assets")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.AssetType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Production.Domain.Entities.AssetAction", b =>
                {
                    b.HasOne("Production.Domain.Entities.Asset", "Asset")
                        .WithMany("Actions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Production.Domain.Entities.AssetLatestFile", b =>
                {
                    b.HasOne("Production.Domain.Entities.Asset", "Asset")
                        .WithOne("LatestFileRef")
                        .HasForeignKey("Production.Domain.Entities.AssetLatestFile", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("Production.Domain.Entities.AssetLatestFile", "FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Production.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Production.Domain.Entities.File", b =>
                {
                    b.HasOne("Production.Domain.Entities.Asset", "Asset")
                        .WithMany("Files")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Production.Domain.Entities.FileAction", b =>
                {
                    b.HasOne("Production.Domain.Entities.File", "File")
                        .WithMany("FileActions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Production.Domain.Entities.FileLatestAction", b =>
                {
                    b.HasOne("Production.Domain.Entities.FileAction", "Action")
                        .WithOne()
                        .HasForeignKey("Production.Domain.Entities.FileLatestAction", "ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.File", "File")
                        .WithOne("LatestAction")
                        .HasForeignKey("Production.Domain.Entities.FileLatestAction", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Production.Domain.Entities.Journal", b =>
                {
                    b.HasOne("Production.Domain.Entities.Typesetter", "DefaultTypesetter")
                        .WithMany()
                        .HasForeignKey("DefaultTypesetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultTypesetter");
                });

            modelBuilder.Entity("Production.Domain.Entities.StageHistory", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", "Article")
                        .WithMany("StageHistories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Production.Domain.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Production.Domain.Entities.Author", b =>
                {
                    b.HasOne("Production.Domain.Entities.Article", null)
                        .WithMany("Authors")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("Production.Domain.Entities.Article", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Assets");

                    b.Navigation("Authors");

                    b.Navigation("Comments");

                    b.Navigation("CurrentStage")
                        .IsRequired();

                    b.Navigation("StageHistories");
                });

            modelBuilder.Entity("Production.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Files");

                    b.Navigation("LatestFileRef")
                        .IsRequired();
                });

            modelBuilder.Entity("Production.Domain.Entities.File", b =>
                {
                    b.Navigation("FileActions");

                    b.Navigation("LatestAction")
                        .IsRequired();
                });

            modelBuilder.Entity("Production.Domain.Entities.Journal", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Production.Domain.Entities.Person", b =>
                {
                    b.Navigation("ArticleActors");
                });
#pragma warning restore 612, 618
        }
    }
}
