
services:
  auth-api:
    image: ${DOCKER_REGISTRY-}auth-api
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Auth.API
        PROJECT_PATH: Services/Auth/Auth.API
  
  journals-api:
    image: ${DOCKER_REGISTRY-}journals-api
    depends_on:
      - journals-redisdb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Journals.API
        PROJECT_PATH: Services/Journals/Journals.API

  articleHub-api:
    image: ${DOCKER_REGISTRY-}articlehub-api
    depends_on:
      - postgres
      - articlehub-hasura
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ArticleHub.API
        PROJECT_PATH: Services/ArticleHub/ArticleHub.API

  submission-api:
    image: ${DOCKER_REGISTRY-}submission-api
    depends_on:
      - sqlserver
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Submission.API
        PROJECT_PATH: Services/Submission/Submission.API

  review-api:
    image: ${DOCKER_REGISTRY-}review-api
    depends_on:
      - sqlserver
      - rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Review.API
        PROJECT_PATH: Services/Review/Review.API

  production-api:
    image: ${DOCKER_REGISTRY-}production-api
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Production.API
        PROJECT_PATH: Services/Production/Production.API

  sqlserver:
    image: mcr.microsoft.com/mssql/server

  journals-redisdb:
    image: redis/redis-stack

  articlehub-hasura:
    image: hasura/graphql-engine
    depends_on:
      - postgres

#talk: separation beetwen main and override files
  postgres:
    image: postgres
    # volumes:
    #   - articlehub_data:/var/lib/postgresql/data/ 

  rabbitmq:
    image: "rabbitmq:management"
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq

volumes:
  articlehub_data:
  rabbitmq_data: