
services:
  submission-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=SubmissionDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True
      # - RabbitMqOptions__Host=amqp://articles-mq:5672
      # - RabbitMqOptions__UserName=guest
      # - RabbitMqOptions__Password=guest 
    ports:
      - "9004:8080"
      - "9054:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  

  production-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=ProductionDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True
    ports:
      - "9002:8080"
      - "9052:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  articleHub-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
#      - ConnectionStrings__Database=Host=localhost;Port=5432;Database=ArticleHubDb;Username=postgres;Password=Password123!
      - ConnectionStrings__Database=Server=postgres;Port=5432;Database=ArticleHubDb;User Id=postgres;Password=Password123!;Include Error Detail=true
 
    ports:
      - "9005:8080"
      - "9055:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  journal-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=redis://journal-redisdb
    ports:
      - "9003:8080"
      - "9053:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  auth-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=AuthDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True
    ports:
      - "9001:8080"
      - "9051:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    restart: always
    ports:
      - "1433:1433" 

  journal-redisdb:
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"

  articlehub-hasura:
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:Password123!@postgres:5432/ArticleHubDb
      - HASURA_GRAPHQL_ADMIN_SECRET=secret
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    ports:
      - "9080:8080"

  postgres:
    # talk: use container_name attribute if you want to give a custom name to the container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=ArticleHubDb
    restart: always
    ports:
        - "5432:5432"

  rabbitmq:
    container_name: "rabbitmq"
    hostname: articles-mq
    restart: always
    ports:
      - "5672:5672"    # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI (accessible at http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest